### ISSUE TITLE
Validation causes TypeError

### ISSUE THREAD

**Issue by Donnyofdoom** [poppinss/indicative#61]
Using indicative 2.1.0
Was having trouble in my build after upgrading from 1.3.x and wrote a sanity script just to make sure.
http://pastebin.com/9gS1084h

Tested with all variations of validate and ValidateAll, with and without message parameter.
Every time it results in this:

> \node_modules\indicative\src\Parser\index.js:60
>  const validationsArray = validations instanceof Array ? validations : validations.split('|')
>                                                                                    ^
> TypeError: validations.split is not a function

As far as I can tell I've followed the new docs to the letter. Am I missing something really obvious that I failed to read or is this a bug?

**Comment by thetutlage** [comment]
Can u share some code sample for me to see

**Comment by Donnyofdoom** [comment]
I did, that's what the pastebin link contains. My sanity code making sure I could reproduce the error consistently.

**Comment by thetutlage** [comment]
`indicative.validate` needs `data` to be 1st and `schema` to be 2nd. http://indicative.adonisjs.com/#indicative-basics-setup

**Comment by Donnyofdoom** [comment]
Ahh I see. Thank you for the clarification. The docs need updating in several places to reflect that, including in the header of the link you attached.
